# ToM-NAS Cloud Run Service Configuration
# Deploy with: gcloud run services replace cloudrun-service.yaml

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: tom-nas-api
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/launch-stage: GA
spec:
  template:
    metadata:
      annotations:
        # Scaling configuration
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/startup-cpu-boost: "true"
        # Execution environment
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: tom-nas-sa@PROJECT_ID.iam.gserviceaccount.com
      containers:
        - image: gcr.io/PROJECT_ID/tom-nas-api:latest
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "2"
              memory: 4Gi
          env:
            - name: TOM_NAS_ENV
              value: production
            - name: TOM_NAS_LOG_LEVEL
              value: INFO
            - name: ENABLE_CLOUD_LOGGING
              value: "true"
            - name: ENABLE_METRICS
              value: "true"
            - name: TOM_NAS_DEVICE
              value: cpu
            - name: GCP_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: gcp-project-id
                  key: latest
          startupProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            periodSeconds: 30
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
